### ISSUE TITLE
gradio_app.py 代码无法运行

### ISSUE THREAD

**Issue by WyHy** [infinigence/Infini-Megrez-Omni#2]
如题，按照环境配置后，
运行时，输入：你是谁？
出现错误：
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.16s/it]
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
/data/conda/envs/MinerU/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:510: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Exception in thread Thread-7 (chat):
Traceback (most recent call last):
  File "/data/conda/envs/MinerU/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/conda/envs/MinerU/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/conda/envs/MinerU/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/.cache/huggingface/modules/transformers_modules/modeling_megrezo.py", line 329, in chat
    data = processor(input_msgs)
  File "/data/.cache/huggingface/modules/transformers_modules/processing_megrezo.py", line 210, in __call__
    prompt = self.tokenizer.apply_chat_template(
  File "/data/conda/envs/MinerU/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1820, in apply_chat_template
    isinstance(conversation[0], (list, tuple)) or hasattr(conversation[0], "messages")
IndexError: list index out of range

**Comment by lizhiyuanUSTC** [comment]
感谢您对Megrez-3B-Omni的关注！

从日志看像是后台没有收到前端输入的消息，您可以在[code](https://github.com/infinigence/Infini-Megrez-Omni/blob/main/gradio_app.py#L133)插入一行确认msgs是否包含您的输入信息

音频输入在网络波动的时候出现过类似的问题，您可以确认下是否有网络波动或者使用代理的情况，如果类似问题仍然出现，能否提供一下您的环境信息我们确认是否是gradio版本的原因

**Comment by imnewbe** [comment]
同样的问题，history2messages(history)返回的list为空。
![image](https://github.com/user-attachments/assets/dad14f91-f0e9-4582-a4b8-aacab5096d45)

**Comment by lizhiyuanUSTC** [comment]
[req.txt](https://github.com/user-attachments/files/18176446/req.txt)

能否参考一下我提供的环境看是否有版本差异，我在本地不能复现出同样的错误来

**Comment by imnewbe** [comment]
> [req.txt](https://github.com/user-attachments/files/18176446/req.txt)
> 
> 能否参考一下我提供的环境看是否有版本差异，我在本地不能复现出同样的错误来
accelerate==1.2.1
aiofiles==23.2.1
aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aiosignal==1.3.2
annotated-types==0.7.0
anyio==4.7.0
async-timeout==5.0.1
attrs==24.3.0
certifi==2024.12.14
charset-normalizer==3.4.0
click==8.1.7
datasets==3.2.0
dill==0.3.8
exceptiongroup==1.2.2
fastapi==0.115.6
ffmpy==0.4.0
filelock==3.16.1
frozenlist==1.5.0
fsspec==2024.9.0
gradio==5.9.1
gradio_client==1.5.2
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
huggingface-hub==0.27.0
idna==3.10
Jinja2==3.1.4
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.16
networkx==3.4.2
numpy==2.2.0
orjson==3.10.12
packaging==24.2
pandas==2.2.3
pillow==11.0.0
propcache==0.2.1
psutil==6.1.0
pyarrow==18.1.0
pydantic==2.10.3
pydantic_core==2.27.1
pydub==0.25.1
Pygments==2.18.0
python-dateutil==2.9.0.post0
python-multipart==0.0.20
pytz==2024.2
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
rich==13.9.4
ruff==0.8.3
safehttpx==0.1.6
safetensors==0.4.5
semantic-version==2.10.0
shellingham==1.5.4
six==1.17.0
sniffio==1.3.1
starlette==0.41.3
sympy==1.13.1
tokenizers==0.21.0
tomlkit==0.13.2
torch==2.5.1
tqdm==4.67.1
transformers==4.47.1
typer==0.15.1
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
uvicorn==0.34.0
websockets==14.1
xxhash==3.5.0
yarl==1.18.3
电脑是mac arm版本

**Comment by imnewbe** [comment]
> > > [req.txt](https://github.com/user-attachments/files/18176446/req.txt)
> > > 能否参考一下我提供的环境看是否有版本差异，我在本地不能复现出同样的错误来
> > 
> > 
> > accelerate==1.2.1 aiofiles==23.2.1 aiohappyeyeballs==2.4.4 aiohttp==3.11.10 aiosignal==1.3.2 annotated-types==0.7.0 anyio==4.7.0 async-timeout==5.0.1 attrs==24.3.0 certifi==2024.12.14 charset-normalizer==3.4.0 click==8.1.7 datasets==3.2.0 dill==0.3.8 exceptiongroup==1.2.2 fastapi==0.115.6 ffmpy==0.4.0 filelock==3.16.1 frozenlist==1.5.0 fsspec==2024.9.0 gradio==5.9.1 gradio_client==1.5.2 h11==0.14.0 httpcore==1.0.7 httpx==0.28.1 huggingface-hub==0.27.0 idna==3.10 Jinja2==3.1.4 markdown-it-py==3.0.0 MarkupSafe==2.1.5 mdurl==0.1.2 mpmath==1.3.0 multidict==6.1.0 multiprocess==0.70.16 networkx==3.4.2 numpy==2.2.0 orjson==3.10.12 packaging==24.2 pandas==2.2.3 pillow==11.0.0 propcache==0.2.1 psutil==6.1.0 pyarrow==18.1.0 pydantic==2.10.3 pydantic_core==2.27.1 pydub==0.25.1 Pygments==2.18.0 python-dateutil==2.9.0.post0 python-multipart==0.0.20 pytz==2024.2 PyYAML==6.0.2 regex==2024.11.6 requests==2.32.3 rich==13.9.4 ruff==0.8.3 safehttpx==0.1.6 safetensors==0.4.5 semantic-version==2.10.0 shellingham==1.5.4 six==1.17.0 sniffio==1.3.1 starlette==0.41.3 sympy==1.13.1 tokenizers==0.21.0 tomlkit==0.13.2 torch==2.5.1 tqdm==4.67.1 transformers==4.47.1 typer==0.15.1 typing_extensions==4.12.2 tzdata==2024.2 urllib3==2.2.3 uvicorn==0.34.0 websockets==14.1 xxhash==3.5.0 yarl==1.18.3 电脑是mac arm版本
> 
> 你是不是点的Regenerate来提交，目前demo里提交方式是文本框里回车或者点击文本框右边的箭头



新的错误又出现了。。。。windows和mac都是一样的错误，前提是没有使用cuda，参数修改为
        model = (
            AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True, torch_dtype=torch.bfloat16)
            .eval()
            .cpu()
        )

**Comment by lizhiyuanUSTC** [comment]
cpu推理速度太慢超时了，您参考https://github.com/infinigence/Infini-Megrez-Omni/issues/4

**Comment by WyHy** [comment]
> 感谢您对Megrez-3B-Omni的关注！
> 
> 从日志看像是后台没有收到前端输入的消息，您可以在[code](https://github.com/infinigence/Infini-Megrez-Omni/blob/main/gradio_app.py#L133)插入一行确认msgs是否包含您的输入信息
> 
> 音频输入在网络波动的时候出现过类似的问题，您可以确认下是否有网络波动或者使用代理的情况，如果类似问题仍然出现，能否提供一下您的环境信息我们确认是否是gradio版本的原因

感谢回复，已经解决了，是使用的问题，我才发现提交问答是用回车或者小飞机，我之前点击的是regenerate 😂，文档中是不是需要稍微做个提示，说明下使用方法
